services:
  agrostellar-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: jounax/h2-agrostellar:v1
    container_name: agrostellar-db-rm560907
    restart: always
    environment:
      H2_VERSION: 2.2.224
      H2_TCP_PORT: 9092
      H2_WEB_PORT: 8082
    ports:
      - "9092:9092"
      - "8082:8082"
    volumes:
      - agrostellar-h2-data:/opt/h2-data
    networks:
      - agrostellar-network

  agrostellar-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jounax/agrostellar-api:v1
    container_name: agrostellar-app-rm560907
    restart: always
    depends_on:
      - agrostellar-db
    environment:
      SPRING_APPLICATION_NAME: agrostellar-api
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:h2:tcp://agrostellar-db:9092/./agrostellar
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect

      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT: 5000

      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console

      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
    ports:
      - "8080:8080"
    networks:
      - agrostellar-network

volumes:
  agrostellar-h2-data:

networks:
  agrostellar-network:
    driver: bridge